/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectpoo;

import Clases.Computador;
import Clases.TiendaElectrodomesticos;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;

/**
 *
 * @author Juanpaa
 */
public class CategoriaComputadoras extends javax.swing.JPanel {
    
    TiendaElectrodomesticos tiendaElectrodomesticos;
   


    /**
     * Creates new form CategoriaComputadoras
     */
    public CategoriaComputadoras() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMarca = new javax.swing.JComboBox<>();
        cbTipo = new javax.swing.JComboBox<>();
        rbEstuche = new javax.swing.JRadioButton();
        rbCooler = new javax.swing.JRadioButton();
        rbMouse = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rbHeadSets = new javax.swing.JRadioButton();
        rbWebcam = new javax.swing.JRadioButton();
        rbParlantes = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbCantidad = new javax.swing.JComboBox<>();

        cbMarca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lenovo", "Asus", "Hp", "Dell" }));
        cbMarca.setEnabled(false);
        cbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMarcaActionPerformed(evt);
            }
        });

        cbTipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Escritorio", " " }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        rbEstuche.setText("Estuche");
        rbEstuche.setEnabled(false);

        rbCooler.setText("Cooler");
        rbCooler.setEnabled(false);

        rbMouse.setText("Mouse");
        rbMouse.setEnabled(false);

        jLabel1.setText("Extras:");

        rbHeadSets.setText("HeadSets");
        rbHeadSets.setEnabled(false);

        rbWebcam.setText("Webcam");
        rbWebcam.setEnabled(false);

        rbParlantes.setText("Parlantes");
        rbParlantes.setEnabled(false);

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad:");

        cbCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMouse)
                            .addComponent(rbCooler)
                            .addComponent(rbEstuche))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbWebcam)
                            .addComponent(rbHeadSets)
                            .addComponent(rbParlantes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnGuardar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbCooler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbEstuche)
                        .addGap(12, 12, 12)
                        .addComponent(rbMouse))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbWebcam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbParlantes)
                        .addGap(12, 12, 12)
                        .addComponent(rbHeadSets)))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        
        cbMarca.setEnabled(true);
        
        
        
    }//GEN-LAST:event_cbTipoActionPerformed

    private void cbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMarcaActionPerformed
        
        rbCooler.setEnabled(true);
        rbEstuche.setEnabled(true);
        rbMouse.setEnabled(true);
        rbWebcam.setEnabled(true);
        rbParlantes.setEnabled(true);
        rbHeadSets.setEnabled(true);
        
        btnGuardar.setEnabled(true);
        
    }//GEN-LAST:event_cbMarcaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        String tipo="";
        String marca="";
        double precioFinal=0;
        double extras=0;
        int cantidad=0;
        //Guardo la cantidad del combo box
        cantidad=Integer.parseInt((String)cbCantidad.getSelectedItem());

        //Calculo el precio de los extras.
        if(rbCooler.isSelected()){
            extras+=60;
        }
        if(rbEstuche.isSelected()){
            extras+=50;
        }
        if(rbMouse.isSelected()){
            extras+=29;
        }
        if(rbWebcam.isSelected()){
            extras+=25;
        }
        if(rbParlantes.isSelected()){
            extras+=33;
        }
        if(rbHeadSets.isSelected()){
            extras+=48;
        }
        

        tipo=(String)cbTipo.getSelectedItem();
        marca=(String)cbMarca.getSelectedItem();
        
        //Creacion del Objeto
        tiendaElectrodomesticos= new Computador(((String)cbTipo.getSelectedItem()),
                "Computadora",cantidad,extras,((String)cbMarca.getSelectedItem()) );
        
        //Calculo el precio final usando el metodo de la clase Computador y le mando
        //a la clase padre
        precioFinal=((Computador)tiendaElectrodomesticos).calcularPrecio();
        tiendaElectrodomesticos.setPrecioFinal(precioFinal);
        
        Array.tiendaArray.add(tiendaElectrodomesticos);
        System.out.println(Array.tiendaArray);
        //TiendaElectrodomesticos.tiendaArray.add(tiendaElectrodomesticos);
        
        //System.out.println(tiendaElectrodomesticos.toString());
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbCantidad;
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbCooler;
    private javax.swing.JRadioButton rbEstuche;
    private javax.swing.JRadioButton rbHeadSets;
    private javax.swing.JRadioButton rbMouse;
    private javax.swing.JRadioButton rbParlantes;
    private javax.swing.JRadioButton rbWebcam;
    // End of variables declaration//GEN-END:variables
}
