/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectpoo;

import Clases.TiendaElectrodomesticos;
import java.awt.BorderLayout;
import java.util.ArrayList;

/**
 *
 * @author Juanpaa
 */
public class PanelAgregarProductos extends javax.swing.JPanel {
    CategoriaComputadoras categoriaComputadoras;
    CategoriaImpresoras categoriaImpresoras;
    CategoriaTelevisiones categoriaTelevisiones;

    /**
     *
     */
    
    

    /**
     * Creates new form PanelAgregarProductos
     */
    public PanelAgregarProductos() {
        
        initComponents();
        categoriaComputadoras = new CategoriaComputadoras();
        categoriaImpresoras = new CategoriaImpresoras();
        categoriaTelevisiones = new CategoriaTelevisiones();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        pnlCategorias = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Categorias:");

        cbCategoria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computadoras", "Impresoras ", "Televisores", " " }));
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCategoriasLayout = new javax.swing.GroupLayout(pnlCategorias);
        pnlCategorias.setLayout(pnlCategoriasLayout);
        pnlCategoriasLayout.setHorizontalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        pnlCategoriasLayout.setVerticalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pnlCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    
    
    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        
        
        
        if(cbCategoria.getSelectedIndex()==0){
            categoriaImpresoras.setVisible(false);
            categoriaTelevisiones.setVisible(false);
            
            pnlCategorias.setLayout(new BorderLayout());
            pnlCategorias.add(categoriaComputadoras, BorderLayout.CENTER);
            
            categoriaComputadoras.setVisible(true);
            revalidate();
            repaint();
            
        }
        if(cbCategoria.getSelectedIndex()==1){
            categoriaTelevisiones.setVisible(false);
            categoriaComputadoras.setVisible(false);
             
            categoriaImpresoras.setVisible(true);
            categoriaImpresoras.setSize(600,600);
            pnlCategorias.add(categoriaImpresoras);
            revalidate();
            repaint();
           
            
            
        }
        if (cbCategoria.getSelectedIndex()==2){
            categoriaImpresoras.setVisible(false);
            categoriaComputadoras.setVisible(false);
            
            pnlCategorias.setLayout(new BorderLayout());
            pnlCategorias.add(categoriaTelevisiones, BorderLayout.CENTER);
            
            categoriaTelevisiones.setVisible(true);
            revalidate();
            repaint();
            
            
        }
     
    }//GEN-LAST:event_cbCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlCategorias;
    // End of variables declaration//GEN-END:variables
}
